### PR TITLE
Issue/564

### LINKED ISSUE #564: Rpm installation errors
Couple things with the rpm:

- [x] Installing from scratch errors when attempting to generate config.yaml
- [x] Installing from scratch doesn't generate a plugin-logging.yaml file
- [x] Upgrading from 2 to 3 doesn't generate config files.
- [x] Upgrading from 2 to 3 generates warnings:
> /var/tmp/rpm-tmp.JOGVtS: line 48: /opt/beer-garden/bin/migrate_bartender_config: No such file or directory
   /var/tmp/rpm-tmp.JOGVtS: line 54: /opt/beer-garden/bin/migrate_brew_view_config: No such file or directory

### PR DESCRIPTION
**Pull request by hazmat345**
This fixes #564.

- It ensures that all three config files are always generated when installing the rpm, if necessary.
- It also changes two config item names related to application logging to make it more clear what they are. They're now prefixed 
with "fallback" to communicate that they'll only be used if a logging config file is not provided.
- The generate methods in the `config` module no longer try to use the yapconf spec to deal with arguments. They require arguments that don't make sense in the overall application configuration, so trying to shoehorn them into the spec was confusing. They now use their own argparser.
- Renamed `logging-config.yaml` to `app-config.yaml` in the example configs directory.

### CODE REVIEW

**Comment by TheBurchLog** [comment]
@hazmat345 I am attempting to build the RPM but I am running in the following problems. I copied all of the repo files from Brewtils into the `/src` of Beer Garden. Is this error expected?

Executed in rpm/bin
```
python build.py --local --python 3.7 --distribution centos7 rpm 3.0.0a1
```

Error Message
```
removing 'beer-garden-3.0.0.dev1' (and everything under it)
make: Leaving directory `/src/app'
cat: /src/brewtils/brewtils/__version__.py: No such file or directory
Requirement '/src/brewtils/dist/brewtils-.tar.gz' looks like a filename, but the file does not exist
Processing /src/brewtils/dist/brewtils-.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/src/brewtils/dist/brewtils-.tar.gz'

```

**Comment by hazmat345** [comment]
You need to clone the brewtils repo into that directory. So there should be src/app, src/ui, and src/brewtils.

**Comment by TheBurchLog** [comment]
@hazmat345 Here are all of the steps I did

```
mkdir rpm-builder
git clone --branch issue/562 https://github.com/beer-garden/beer-garden.git rpm-builder/
mkdir rpm-builder-brewtils
git clone --branch v3 https://github.com/beer-garden/brewtils.git rpm-builder-brewtils
mv rpm-builder-brewtils/* rpm-builder/src/
cd rpm-builder/rpm/bin/

rm src/ui/package-lock.json

python3 build.py --local --python 3.7 --distribution centos7 rpm 3.0.0a1

```

Command output
```
make: Entering directory '/src/ui'
rm -rf dist
echo "TODO: clean javascript tests"
TODO: clean javascript tests
rm -f npm-debug.log
rm -f npm-error.log
npm run build

> beer_garden@0.0.1 build /src/ui
> webpack --config webpack.prod.js

sh: 1: webpack: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! beer_garden@0.0.1 build: `webpack --config webpack.prod.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the beer_garden@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-25T11_31_46_880Z-debug.log
Makefile:69: recipe for target 'package' failed
make: Leaving directory '/src/ui'
make: *** [package] Error 1
make: *** No rule to make target `package-source'.  Stop.
make: Entering directory `/src/brewtils'
make: Leaving directory `/src/brewtils'
make: Entering directory `/src/app'
/opt/beer-garden/bin/python setup.py sdist
running sdist
running egg_info
writing beer_garden.egg-info/PKG-INFO
writing dependency_links to beer_garden.egg-info/dependency_links.txt
writing entry points to beer_garden.egg-info/entry_points.txt
writing requirements to beer_garden.egg-info/requires.txt
writing top-level names to beer_garden.egg-info/top_level.txt
reading manifest file 'beer_garden.egg-info/SOURCES.txt'
writing manifest file 'beer_garden.egg-info/SOURCES.txt'
running check
creating beer-garden-3.0.0.dev1
creating beer-garden-3.0.0.dev1/beer_garden
creating beer-garden-3.0.0.dev1/beer_garden.egg-info
creating beer-garden-3.0.0.dev1/beer_garden/api
creating beer-garden-3.0.0.dev1/beer_garden/api/http
creating beer-garden-3.0.0.dev1/beer_garden/api/http/handlers
creating beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
creating beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/vbeta
creating beer-garden-3.0.0.dev1/beer_garden/api/thrift
creating beer-garden-3.0.0.dev1/beer_garden/db
creating beer-garden-3.0.0.dev1/beer_garden/db/mongo
creating beer-garden-3.0.0.dev1/beer_garden/events
creating beer-garden-3.0.0.dev1/beer_garden/local_plugins
creating beer-garden-3.0.0.dev1/beer_garden/queue
copying files to beer-garden-3.0.0.dev1...
copying README.rst -> beer-garden-3.0.0.dev1
copying setup.cfg -> beer-garden-3.0.0.dev1
copying setup.py -> beer-garden-3.0.0.dev1
copying beer_garden/__init__.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/__main__.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/__version__.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/app.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/commands.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/config.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/errors.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/garden.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/instances.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/log.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/metrics.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/monitor.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/namespace.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/plugin.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/queues.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/requests.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/router.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/scheduler.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden/systems.py -> beer-garden-3.0.0.dev1/beer_garden
copying beer_garden.egg-info/PKG-INFO -> beer-garden-3.0.0.dev1/beer_garden.egg-info
copying beer_garden.egg-info/SOURCES.txt -> beer-garden-3.0.0.dev1/beer_garden.egg-info
copying beer_garden.egg-info/dependency_links.txt -> beer-garden-3.0.0.dev1/beer_garden.egg-info
copying beer_garden.egg-info/entry_points.txt -> beer-garden-3.0.0.dev1/beer_garden.egg-info
copying beer_garden.egg-info/requires.txt -> beer-garden-3.0.0.dev1/beer_garden.egg-info
copying beer_garden.egg-info/top_level.txt -> beer-garden-3.0.0.dev1/beer_garden.egg-info
copying beer_garden/api/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/api
copying beer_garden/api/entry_point.py -> beer-garden-3.0.0.dev1/beer_garden/api
copying beer_garden/api/http/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/authorization.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/base_handler.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/client.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/metrics.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/processors.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/publishers.py -> beer-garden-3.0.0.dev1/beer_garden/api/http
copying beer_garden/api/http/handlers/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers
copying beer_garden/api/http/handlers/misc.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers
copying beer_garden/api/http/handlers/v1/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/admin.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/command.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/event.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/forward.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/garden.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/instance.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/job.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/logging.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/namespace.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/permissions.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/queue.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/request.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/role.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/system.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/token.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/v1/user.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/v1
copying beer_garden/api/http/handlers/vbeta/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/vbeta
copying beer_garden/api/http/handlers/vbeta/event.py -> beer-garden-3.0.0.dev1/beer_garden/api/http/handlers/vbeta
copying beer_garden/api/thrift/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/api/thrift
copying beer_garden/api/thrift/client.py -> beer-garden-3.0.0.dev1/beer_garden/api/thrift
copying beer_garden/api/thrift/handler.py -> beer-garden-3.0.0.dev1/beer_garden/api/thrift
copying beer_garden/api/thrift/server.py -> beer-garden-3.0.0.dev1/beer_garden/api/thrift
copying beer_garden/db/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/db
copying beer_garden/db/api.py -> beer-garden-3.0.0.dev1/beer_garden/db
copying beer_garden/db/mongo/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/api.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/fields.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/jobstore.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/models.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/parser.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/pruner.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/db/mongo/util.py -> beer-garden-3.0.0.dev1/beer_garden/db/mongo
copying beer_garden/events/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/events
copying beer_garden/events/handlers.py -> beer-garden-3.0.0.dev1/beer_garden/events
copying beer_garden/events/processors.py -> beer-garden-3.0.0.dev1/beer_garden/events
copying beer_garden/local_plugins/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/local_plugins
copying beer_garden/local_plugins/env_help.py -> beer-garden-3.0.0.dev1/beer_garden/local_plugins
copying beer_garden/local_plugins/manager.py -> beer-garden-3.0.0.dev1/beer_garden/local_plugins
copying beer_garden/local_plugins/runner.py -> beer-garden-3.0.0.dev1/beer_garden/local_plugins
copying beer_garden/queue/__init__.py -> beer-garden-3.0.0.dev1/beer_garden/queue
copying beer_garden/queue/api.py -> beer-garden-3.0.0.dev1/beer_garden/queue
copying beer_garden/queue/rabbit.py -> beer-garden-3.0.0.dev1/beer_garden/queue
Writing beer-garden-3.0.0.dev1/setup.cfg
Creating tar archive
removing 'beer-garden-3.0.0.dev1' (and everything under it)
make: Leaving directory `/src/app'
cat: /src/brewtils/brewtils/__version__.py: No such file or directory
Requirement '/src/brewtils/dist/brewtils-.tar.gz' looks like a filename, but the file does not exist
Processing /src/brewtils/dist/brewtils-.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/src/brewtils/dist/brewtils-.tar.gz'

You are using pip version 19.0.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cp: cannot stat ‘/src/ui/dist’: No such file or directory
Building beer-garden (3.0.0a1) RPM Package...
{:timestamp=>"2020-08-25T11:31:52.600664+0000", :message=>"Force flag given. Overwriting package at beer-garden-3.0.0a1-1.el7.x86_64.rpm", :level=>:warn}

```

**Comment by hazmat345** [comment]
@TheBurchLog see my last comment. Please verify that you have

- src/app
- src/ui
- **src/brewtils**

----
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?

You need to run `npm install`

**Comment by TheBurchLog** [comment]
@hazmat345 
:anger: brewtils == repo not folder brewtils in repo

New build steps:
```
mkdir rpm-builder;
git clone --branch issue/562 https://github.com/beer-garden/beer-garden.git rpm-builder/;
mkdir rpm-builder-brewtils;
git clone --branch v3 https://github.com/beer-garden/brewtils.git rpm-builder-brewtils;
mkdir rpm-builder/src/brewtils;
mv rpm-builder-brewtils/* rpm-builder/src/brewtils;

npm --prefix ./rpm-builder/src/ui/ install ./rpm-builder/src/ui/;

rm src/ui/package-lock.json;
cd rpm-builder/rpm/bin/;

python3 build.py --local --python 3.7 --distribution centos7 rpm 3.0.0a1;
```

Looks like it build that time. Going to trying installing it on a fresh VM.

**Comment by TheBurchLog** [comment]
On a clean VM I have RabbitMQ and MongoDB running in Docker images. Then I attempted to run the RPM installer. Here is the result.

```
sudo rpm -i beer-garden-3.0.0a1-1.el7.x86_64.rpm 
usage: generate_config [-h] [--publish-hostname PUBLISH_HOSTNAME]
                       [--mq-host MQ.HOST]
                       [--mq-admin-queue-expiry MQ.ADMIN_QUEUE_EXPIRY]
                       [--mq-heartbeat-interval MQ.HEARTBEAT_INTERVAL]
                       [--mq-blocked-connection-timeout MQ.BLOCKED_CONNECTION_TIMEOUT]
                       [--mq-connection-attempts MQ.CONNECTION_ATTEMPTS]
                       [--mq-exchange MQ.EXCHANGE]
                       [--mq-virtual-host MQ.VIRTUAL_HOST]
                       [--mq-connections-admin-port MQ.CONNECTIONS.ADMIN.PORT]
                       [--mq-connections-admin-user MQ.CONNECTIONS.ADMIN.USER]
                       [--mq-connections-admin-password MQ.CONNECTIONS.ADMIN.PASSWORD]
                       [--mq-connections-admin-ssl-no-enabled | --mq-connections-admin-ssl-enabled]
                       [--mq-connections-admin-ssl-ca-cert MQ.CONNECTIONS.ADMIN.SSL.CA_CERT]
                       [--mq-connections-admin-ssl-no-ca-verify | --mq-connections-admin-ssl-ca-verify]
                       [--mq-connections-admin-ssl-client-cert MQ.CONNECTIONS.ADMIN.SSL.CLIENT_CERT]
                       [--mq-connections-message-port MQ.CONNECTIONS.MESSAGE.PORT]
                       [--mq-connections-message-password MQ.CONNECTIONS.MESSAGE.PASSWORD]
                       [--mq-connections-message-user MQ.CONNECTIONS.MESSAGE.USER]
                       [--mq-connections-message-ssl-no-enabled | --mq-connections-message-ssl-enabled]
                       [--mq-connections-message-ssl-ca-cert MQ.CONNECTIONS.MESSAGE.SSL.CA_CERT]
                       [--mq-connections-message-ssl-no-ca-verify | --mq-connections-message-ssl-ca-verify]
                       [--mq-connections-message-ssl-client-cert MQ.CONNECTIONS.MESSAGE.SSL.CLIENT_CERT]
                       [--application-no-cors-enabled | --application-cors-enabled]
                       [--application-no-debug-mode | --application-debug-mode]
                       [--application-name APPLICATION.NAME]
                       [--application-icon-default APPLICATION.ICON_DEFAULT]
                       [--application-no-allow-unsafe-templates | --application-allow-unsafe-templates]
                       [--auth-no-enabled | --auth-enabled]
                       [--auth-no-guest-login-enabled | --auth-guest-login-enabled]
                       [--auth-token-algorithm AUTH.TOKEN.ALGORITHM]
                       [--auth-token-lifetime AUTH.TOKEN.LIFETIME]
                       [--auth-token-secret AUTH.TOKEN.SECRET]
                       [--configuration-file CONFIGURATION.FILE]
                       [--db-name DB.NAME]
                       [--db-connection-host DB.CONNECTION.HOST]
                       [--db-connection-password DB.CONNECTION.PASSWORD]
                       [--db-connection-port DB.CONNECTION.PORT]
                       [--db-connection-username DB.CONNECTION.USERNAME]
                       [--db-ttl-event DB.TTL.EVENT]
                       [--db-ttl-action DB.TTL.ACTION]
                       [--db-ttl-info DB.TTL.INFO]
                       [--entry-http-no-enable | --entry-http-enable]
                       [--entry-http-ssl-no-enabled | --entry-http-ssl-enabled]
                       [--entry-http-ssl-private-key ENTRY.HTTP.SSL.PRIVATE_KEY]
                       [--entry-http-ssl-public-key ENTRY.HTTP.SSL.PUBLIC_KEY]
                       [--entry-http-ssl-ca-cert ENTRY.HTTP.SSL.CA_CERT]
                       [--entry-http-ssl-ca-path ENTRY.HTTP.SSL.CA_PATH]
                       [--entry-http-ssl-client-cert-verify ENTRY.HTTP.SSL.CLIENT_CERT_VERIFY]
                       [--entry-http-port ENTRY.HTTP.PORT]
                       [--entry-http-url-prefix ENTRY.HTTP.URL_PREFIX]
                       [--entry-http-host ENTRY.HTTP.HOST]
                       [--entry-http-public-fqdn ENTRY.HTTP.PUBLIC_FQDN]
                       [--entry-thrift-no-enable | --entry-thrift-enable]
                       [--event-mq-no-enable | --event-mq-enable]
                       [--event-mq-exchange EVENT.MQ.EXCHANGE]
                       [--event-mq-virtual-host EVENT.MQ.VIRTUAL_HOST]
                       [--event-mongo-no-enable | --event-mongo-enable]
                       [--parent-http-no-enable | --parent-http-enable]
                       [--parent-http-ssl-no-enabled | --parent-http-ssl-enabled]
                       [--parent-http-ssl-private-key PARENT.HTTP.SSL.PRIVATE_KEY]
                       [--parent-http-ssl-public-key PARENT.HTTP.SSL.PUBLIC_KEY]
                       [--parent-http-ssl-ca-cert PARENT.HTTP.SSL.CA_CERT]
                       [--parent-http-ssl-ca-path PARENT.HTTP.SSL.CA_PATH]
                       [--parent-http-ssl-client-cert-verify PARENT.HTTP.SSL.CLIENT_CERT_VERIFY]
                       [--parent-http-port PARENT.HTTP.PORT]
                       [--parent-http-url-prefix PARENT.HTTP.URL_PREFIX]
                       [--parent-http-host PARENT.HTTP.HOST]
                       [--parent-http-public-fqdn PARENT.HTTP.PUBLIC_FQDN]
                       [--parent-http-skip-events PARENT.HTTP.SKIP_EVENTS]
                       [--garden-name GARDEN.NAME]
                       [--log-config-file LOG.CONFIG_FILE]
                       [--log-file LOG.FILE] [--log-level LOG.LEVEL]
                       [--metrics-prometheus-no-enabled | --metrics-prometheus-enabled]
                       [--metrics-prometheus-host METRICS.PROMETHEUS.HOST]
                       [--metrics-prometheus-port METRICS.PROMETHEUS.PORT]
                       [--metrics-prometheus-url METRICS.PROMETHEUS.URL]
                       [--plugin-logging-config-file PLUGIN.LOGGING.CONFIG_FILE]
                       [--plugin-logging-fallback-level PLUGIN.LOGGING.FALLBACK_LEVEL]
                       [--plugin-status-heartbeat PLUGIN.STATUS_HEARTBEAT]
                       [--plugin-status-timeout PLUGIN.STATUS_TIMEOUT]
                       [--plugin-local-auth-username PLUGIN.LOCAL.AUTH.USERNAME]
                       [--plugin-local-auth-password PLUGIN.LOCAL.AUTH.PASSWORD]
                       [--plugin-local-directory PLUGIN.LOCAL.DIRECTORY]
                       [--plugin-local-timeout-shutdown PLUGIN.LOCAL.TIMEOUT.SHUTDOWN]
                       [--plugin-local-timeout-startup PLUGIN.LOCAL.TIMEOUT.STARTUP]
                       [--scheduler-auth-username SCHEDULER.AUTH.USERNAME]
                       [--scheduler-auth-password SCHEDULER.AUTH.PASSWORD]
                       [--scheduler-max-workers SCHEDULER.MAX_WORKERS]
                       [--scheduler-job_defaults-no-coalesce | --scheduler-job_defaults-coalesce]
                       [--scheduler-job_defaults-max-instances SCHEDULER.JOB_DEFAULTS.MAX_INSTANCES]
                       [--validator-command-timeout VALIDATOR.COMMAND.TIMEOUT]
                       [--validator-url-ca-cert VALIDATOR.URL.CA_CERT]
                       [--validator-url-no-ca-verify | --validator-url-ca-verify]
generate_config: error: unrecognized arguments: --plugin-local-log-directory /opt/beer-garden/log/plugins

```

**Comment by hazmat345** [comment]
@TheBurchLog I just rebased this onto v3. It should be OK now.

**Comment by TheBurchLog** [comment]
In a clean install VM I ran into the following error:

```
sudo rpm -i beer-garden-3.0.0a1-1.el7.x86_64.rpm 
/var/tmp/rpm-tmp.b1nIjw: line 63: [: missing `]'
/var/tmp/rpm-tmp.b1nIjw: line 66: [: missing `]'
```

Here are my install instructions I used:

Build RPM
```
mkdir rpm-builder;
git clone --branch issue/564 https://github.com/beer-garden/beer-garden.git rpm-builder/;
mkdir rpm-builder-brewtils;
git clone --branch v3 https://github.com/beer-garden/brewtils.git rpm-builder-brewtils;
mkdir rpm-builder/src/brewtils;
mv rpm-builder-brewtils/* rpm-builder/src/brewtils;

npm --prefix ./rpm-builder/src/ui/ install ./rpm-builder/src/ui/;

rm rpm-builder/src/ui/package-lock.json
cd rpm-builder/rpm/bin/;

python3 build.py --local --python 3.7 --distribution centos7 rpm 3.0.0a1;
```
Push RPM
```
cd rpm-builder/rpm/dist
sftp x.x.x.x

put beer-garden-3.0.0a1-1.el7.x86_64.rpm
```
Setup VM
```
ssh x.x.x.x

#Install/Start Docker
yum install -y docker
# Adds docker to the startup list
systemctl enable docker.service
systemctl start docker
 
#Install Docker Compose
curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

git clone https://github.com/beer-garden/beer-garden.git
cd beer-garden/
git checkout v3
cd beer-garden/docker/docker-compose

sudo docker-compose up -d mongodb rabbitmq
```
RPM Install
```
sudo rpm -i beer-garden-3.0.0a1-1.el7.x86_64.rpm

```

**Comment by hazmat345** [comment]
@TheBurchLog good catch, that error isn't as apparent when you're using `yum`. Should be fixed now.

**Pull request merged**
