### PR TITLE
Storing request index length in local storage

### PR DESCRIPTION
**Pull request by hazmat345**
This starts addressing #560. Only the request index page is done, but the solution should be easy to expand to the other tables.

### CODE REVIEW

**Review by TheBurchLog — APPROVED** [review]
Works as long as you don't break the session.

**Comment by hazmat345** [comment]
@TheBurchLog not sure what you mean here - what caused it to break?

**Comment by TheBurchLog** [comment]
@hazmat345 
When I meant by breaking the session is going to a new tab or refreshing the page. Our cookies are session based, not browser based.

**Comment by hazmat345** [comment]
@TheBurchLog ahh ok. I'm good with that :smile:

**Pull request merged**
