### PR TITLE
Adding content-type for JS output

### PR DESCRIPTION
**Pull request by hazmat345**
Adds the correct content-type for JS output.

### CODE REVIEW

**Comment by TheBurchLog** [comment]
@hazmat345 Can you add this change to the request_view.js? Right now it won't populate the output field because we are doing a hard filter on output types.

**Comment by hazmat345** [comment]
@TheBurchLog are you sure? It just shows up as normal text for me, which is what I would expect. I didn't make any effort to prettify it since the only use-case I see for this is for "helper" commands that shouldn't be called from the UI anyway.

**Comment by TheBurchLog** [comment]
I didn't actually write a plugin to test this.... so I was just assuming it would fail.... sorry about that. We shouldn't make a helper class to pretty it. I see this PR as a go now :smile:

**Comment by hazmat345** [comment]
I'm going to close this in favor of #539

**Pull request closed without merging**
