### PR TITLE
Added Delete System to routable

### PR DESCRIPTION
**Pull request by TheBurchLog**
Added the Delete System to forwarding options

### CODE REVIEW

**Comment by hazmat345** [comment]
OK, I figured out the problem I was seeing. Try this:

1. Start the parent garden with Plugin A.
2. Stop the parent garden.
3. Start the parent garden with Plugin B.
4. Start the child garden with plugin C.

So now the parent garden should know about A, B, and C. A is stopped, B and C are running.

Now try to delete A. Instead of deleting it I see the parent garden attempt to route that to the child, which is wrong.

**Comment by TheBurchLog** [comment]
Before I got through testing this, when you say "with Plugin A", do you mean that it is a local plugin? Then in the second start, you remove the local plugin and add a new one?

**Comment by hazmat345** [comment]
Yes, that's accurate.

**Comment by TheBurchLog** [comment]
Just ran this scenario with Remote  Plugins, and everything worked as expected. Going to try it with local plugins next.

**Comment by TheBurchLog** [comment]
Just did the scenario:
1) Install Plugin A locally on Parent
2) Start Parent
3) Stop Parent
4) Uninstall Plugin A on Parent
5) Install Plugin B Locally on Parent
6) Start Parent
7) Install Plugin C Remotely on Child
8) Start Child
9) Delete Plugin A on Parent
10) Waited/refreshed, then it was removed successfully

**Comment by TheBurchLog** [comment]
Followed the example you initially provided, and cannot replicate it.

**Comment by hazmat345** [comment]
Alrighty, we can go ahead and merge this. I'm still not sure what's going on, but at this point I don't believe it's an issue with *these* changes.

**Pull request merged**
