### PR TITLE
Issue 375

### LINKED ISSUE #375: Client Cert Login
We should be able to use client certs as an authentication method.

1. Allow users to auto login with certs instead of click the login option
2. Generate tokens based off the cert information
3. Make the cert extraction configurable

### PR DESCRIPTION
**Pull request by TheBurchLog**
This fixes #375. Allowing users to login with trusted certs

- [x] Verified that it still works when not in SSL
- [x] Verify that it still work when in SSL and user not in DB
- [x] Verify that auto login works
- [x] Verify that users can change to admin account in SSL
- [x] Verify that users can log into admin account not in SSL
- [x] Update SSL configuration documents

### CODE REVIEW

**Comment by loganasherjones** [comment]
Do we know if we're merging #370 in before this one or not? There will be lots of conflicts either way.

**Comment by hazmat345** [comment]
I'd say probably this one before #370? That one is pretty raw and I'm not sure how much value it adds. It may be easier to just start from when this gets pulled into v3.

**Comment by hazmat345** [comment]
@TheBurchLog would you like me to add a review on this? I haven't added any comments as it's marked WIP but I can take a look if you'd like.

**Comment by TheBurchLog** [comment]
@hazmat345 We had talked about merging in the changes into this branch. Do you think we should still do that. I saw your comment about moving it over into v3 after these changes go in.

**Review by hazmat345 — COMMENTED** [review]
Converting to draft - we'll need to completely revisit this.

**Comment by TheBurchLog** [comment]
This is OBE now with the changes in https://github.com/beer-garden/beer-garden/pull/855 and NGINX proxy examples.

**Pull request closed without merging**
