### PR TITLE
Global systems

### PR DESCRIPTION
**Pull request by hazmat345**
This PR adds a `systems` attribute on the `rootScope` that is updated as systems are created, removed, and updated.

It also removes most of the references to the global namespace.

### CODE REVIEW

**Comment by TheBurchLog** [comment]
I am going through the UI and some stuff is currently broken.
* `Make It Happen` on System Pages
* Command Hyperlink on Requests Page
* 'Explore Commands' on Home Page

I am going to start reworking these pages to allows to navigation up/down from Namespace to Version.

**Comment by TheBurchLog** [comment]
Uploaded my changes to get everything to work. Let me know what you think of them.

**Comment by TheBurchLog** [comment]
Merged in so we can continue with UI refactor

**Comment by hazmat345** [comment]
Thank you for the fixes @TheBurchLog - they all LGTM!

**Pull request merged**
