### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by hazmat345**
This will run our integration tests on Travis.

### CODE REVIEW

**Comment by loganasherjones** [comment]
🤤 I can't wait for this :)

**Comment by hazmat345** [comment]
@loganasherjones please review when you get a chance. I think the Python 3.4 and 3.5 issues are real issues that need to be fixed elsewhere.

**Comment by hazmat345** [comment]
I think this is the issue... https://docs.python.org/3/whatsnew/3.6.html#json

**Comment by hazmat345** [comment]
This should be good to go once beer-garden/brewtils#48 is done.

**Comment by loganasherjones** [comment]
Looks good!

**Pull request merged**
